is:
  - headers.acceptJson
  - headers.contentTypeJson
  - headers.testScenarioHeader
  - errors.formatVrn
  - errors.formatPeriodKey
  - errors.incorrectOrEmptyBody
  - errors.formatValue
  - errors.ruleNotFinalised
  - errors.formatUniqueId
displayName: Sample Submit Endpoint [test only]
description: This endpoint allows a user to see an example submit endpoint.
(annotations.sandboxData): !include ../scenarios/submit_VatReturn_scenarios.md
(annotations.scope): "write:vat"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:vat" ] } ]
body:
  application/json:
    type: !include ../schemas/submit_VatReturn_request.json
    examples:
     example-1:
      description: sample request body
      value: !include ../examples/submit_request.json
responses:
  200:
    body:
      application/json:
        type: !include ../schemas/submit_VatReturn_response.json
        examples:
          example-1:
            description: Sample example 1
            value: !include ../examples/example_1.json
          example-2:
            description: Sample example 2
            value: !include ../examples/example_2.json
    headers:
      X-CorrelationId:
        example: a1e8057e-fbbc-47a8-a8b4-78d9f015c253
        description: Unique ID for operation tracking <br> String, 36 characters.