#%RAML 1.0 Library
uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml
traits:
  formatVrn:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatVrn:
                description: 'The format of the supplied VRN field is not valid.'
                value:
                  code: FORMAT_VRN
  formatPeriodKey:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatPeriodKey:
                description: 'The format of the supplied period key is not valid. It must be a 4 character string.'
                value:
                  code: FORMAT_PERIOD_KEY
  incorrectOrEmptyBody:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              incorrectOrEmptyBody:
                description: 'An empty or non-matching body was submitted.'
                value:
                  code: RULE_INCORRECT_OR_EMPTY_BODY_SUBMITTED
  formatValue:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatValue:
                description: 'One or more values have been added with the incorrect format.'
                value:
                  code: FORMAT_VALUE
  formatUniqueId:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatUniqueId:
                description: 'The format of the Unique ID is invalid.'
                value:
                  code: FORMAT_UNIQUE_ID
  formatReceivedAt:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatReceivedAt:
                description: 'The format of Received At is invalid.'
                value:
                  code: FORMAT_RECEIVED_AT