#%RAML 1.0 Library

uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

traits:
  nameOfParameter:
    queryParameters:
      nameOfParameter:
        description: "desc"
        example: "example"
        required: false